# Generated by Django 3.2.16 on 2023-02-15 15:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='/static/img/default-profile-image.png', max_length=255, verbose_name='profile_pic'),
        ),
    ]
