# Generated by Django 3.2.16 on 2023-02-15 17:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='static/img/default-profile-pic.png', max_length=255, verbose_name='profile_pic'),
        ),
    ]
