# Generated by Django 3.2.16 on 2023-02-28 12:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='Background Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='Profile Picture'),
        ),
    ]
