# Generated by Django 3.2.16 on 2023-03-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='is_read',
        ),
    ]
